POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "Title Of the Task",
  "dueDate": "2025-01-01T12:00:00Z",
  "description": "Lorem5 ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lobortis diam vel malesuada ultricies.",
  "priority": "normal",
  "status": "todo"
}

